export const THEME = {
	close: "var(--ctp-surface-0)",
	selected: "var(--ctp-blue)",
	adjacent: "var(--ctp-surface-1)",
	hint: "var(--ctp-peach)",
	mine: "var(--ctp-red)",
	flag: "var(--ctp-green)",
	open: "var(--ctp-base)",
	contrast: "var(--ctp-crust)",
	dangers: [
		"var(--ctp-green)",
		"var(--ctp-teal)",
		"var(--ctp-yellow)",
		"var(--ctp-peach)",
		"var(--ctp-maroon)",
		"var(--ctp-red)",
		"var(--ctp-mauve)",
		"var(--ctp-pink)",
	],
};
